# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.enhancer.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'enhancer', 'function_path': 'animated_java:enhancer/variants/default/apply'}
execute on passengers if entity @s[tag=aj.enhancer.bone.bone2] run function animated_java:enhancer/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.enhancer.bone.scanner] run function animated_java:enhancer/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.enhancer.bone.bone] run function animated_java:enhancer/variants/default/zzz/2