# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.mech_torso.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mech_torso', 'function_path': 'animated_java:mech_torso/variants/sword_left/apply'}
execute on passengers if entity @s[tag=aj.mech_torso.bone.barrel1] run function animated_java:mech_torso/variants/sword_left/zzz/apply_to_bone_barrel1
execute on passengers if entity @s[tag=aj.mech_torso.bone.barrel2] run function animated_java:mech_torso/variants/sword_left/zzz/apply_to_bone_barrel2
execute on passengers if entity @s[tag=aj.mech_torso.bone.blaster_left] run function animated_java:mech_torso/variants/sword_left/zzz/apply_to_bone_blaster_left
execute on passengers if entity @s[tag=aj.mech_torso.bone.sword_left] run function animated_java:mech_torso/variants/sword_left/zzz/apply_to_bone_sword_left
execute on passengers if entity @s[tag=aj.mech_torso.bone.rocket_left] run function animated_java:mech_torso/variants/sword_left/zzz/apply_to_bone_rocket_left
execute on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_left1] run function animated_java:mech_torso/variants/sword_left/zzz/apply_to_bone_drillhead_left1
execute on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_left2] run function animated_java:mech_torso/variants/sword_left/zzz/apply_to_bone_drillhead_left2
execute on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_left3] run function animated_java:mech_torso/variants/sword_left/zzz/apply_to_bone_drillhead_left3
execute on passengers if entity @s[tag=aj.mech_torso.bone.drill_left] run function animated_java:mech_torso/variants/sword_left/zzz/apply_to_bone_drill_left
return 1