# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.assembler.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'assembler', 'function_path': 'animated_java:assembler/animations/ring_loop/next_frame'}
execute if score @s aj.ring_loop.frame matches 201.. run scoreboard players set @s aj.ring_loop.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.ring_loop.frame
execute at @s run function animated_java:assembler/animations/ring_loop/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.ring_loop.frame 1