# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.bone21] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone21 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.arm4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_arm4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.small_arm_base4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_small_arm_base4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.bone25] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone25 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.bone16] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone16 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.arm3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_arm3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.small_arm_base3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_small_arm_base3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.bone15] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone15 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.bone26] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone26 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.arm5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_arm5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.small_arm_base5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_small_arm_base5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.bone20] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone20 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.bone11] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.small_arm_base2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_small_arm_base2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.bone2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.ring] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_ring set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.wheel] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_wheel set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.wheel2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_wheel2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.rails] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rails set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.wheel3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_wheel3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.wheel4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_wheel4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.rails2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rails2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.bone6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.bone5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.bone4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.bone3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.octagon] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_octagon set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.machine_arm_root] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_machine_arm_root set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.bone10] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.bone9] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.bone8] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.bone7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.octagon2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_octagon2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.machine_arm_root2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_machine_arm_root2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.node.base] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_base set from storage aj:uuid main.out