# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.compressor.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'compressor', 'function_path': 'animated_java:compressor/animations/compress/next_frame'}
execute if score @s aj.compress.frame matches 13.. run scoreboard players set @s aj.compress.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.compress.frame
execute at @s run function animated_java:compressor/animations/compress/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.compress.frame 1