# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.buggy.bone.antenna] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_antenna set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.buggy.bone.hexadecagon] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hexadecagon set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.buggy.bone.hexadecagon2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hexadecagon2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.buggy.bone.hexadecagon3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hexadecagon3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.buggy.bone.hexadecagon4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hexadecagon4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.buggy.bone.root] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_root set from storage aj:uuid main.out