# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:compressor/animations/compress/zzz/apply_frame {frame: 12}
scoreboard players add @s aj.compress.frame 1