# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:mech_torso/animations/gatling_shooting_r/zzz/apply_frame {frame: 9}
scoreboard players add @s aj.gatling_shooting_r.frame 1