# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:mech_torso/animations/drill_drill_l/zzz/apply_frame {frame: 8}
scoreboard players add @s aj.drill_drill_l.frame 1