# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_legs.bone.foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_legs.bone.leg_low] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_low set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_legs.bone.bone4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_legs.bone.leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_legs.bone.foot2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_foot2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_legs.bone.leg_low2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_low2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_legs.bone.bone3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_legs.bone.leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_legs.bone.hips] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hips set from storage aj:uuid main.out