# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.rocket.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'rocket', 'function_path': 'animated_java:rocket/animations/rocket.button_push/stop'}
tag @s remove aj.rocket.animation.rocket.button_push.playing
scoreboard players set @s aj.rocket.button_push.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:rocket/animations/rocket.button_push/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only