# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.barrel_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_barrel_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.blaster_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_blaster_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.sword_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sword_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.rocket_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rocket_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_drillhead_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_left2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_drillhead_left2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_drillhead_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.drill_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_drill_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.left_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.left_arm_low] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm_low set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_drillhead_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_right2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_drillhead_right2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_right3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_drillhead_right3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.drill_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_drill_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.barrel_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_barrel_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.blaster_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_blaster_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.rocket_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rocket_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.sword_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sword_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.right_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.right_arm_low] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm_low set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.bone.torso] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_torso set from storage aj:uuid main.out