# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:mech_torso/animations/walking_right/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.walking_right.frame 1