# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.enhancer.root] run return 0
execute on passengers if entity @s[tag=aj.enhancer.data] unless data entity @s {data:{rigHash: '24abb1eaa7b109568d8691ae9244f0d662b444349bfe13760dfa922754ee10b1'}} on vehicle run function animated_java:enhancer/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1