# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.enhancer.root] run return 0
execute on passengers if entity @s[tag=aj.enhancer.data] unless data entity @s {data:{rigHash: 'd813f08e346321a9a47fe322a701fb6f89ea1bc2cf0f9d0485a3880531669af1'}} on vehicle run function animated_java:enhancer/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1