# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:enhancer/animations/scanning/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.scanning.frame 1