# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_foot) {transformation: [-1f,0f,0f,0.782f,0f,1f,0f,-1.9926f,0f,0f,-1f,0.3297f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_low) {transformation: [-1f,0f,0f,0.8125f,0f,1f,0f,-0.8712f,0f,0f,-1f,0.0947f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [-1f,0f,0f,0.8125f,0f,0.2588f,0.9659f,-0.713f,0f,0.9659f,-0.2588f,0.6274f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg) {transformation: [-1f,0f,0f,0.8227f,0f,0.7071f,-0.7071f,-0.1971f,0f,-0.7071f,-0.7071f,0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_foot2) {transformation: [-1f,0f,0f,-0.782f,0f,1f,0f,-1.9926f,0f,0f,-1f,0.3297f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_low2) {transformation: [-1f,0f,0f,-0.8125f,0f,1f,0f,-0.8712f,0f,0f,-1f,0.0947f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-1f,0f,0f,-0.8125f,0f,0.2588f,0.9659f,-0.713f,0f,0.9659f,-0.2588f,0.6274f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.8227f,0f,0.7071f,-0.7071f,-0.1971f,0f,-0.7071f,-0.7071f,0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hips) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.1996f,0f,0f,-1f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"commands":{"posx":0,"posy":0,"posz":0,"roty":0,"rotx":0}}}