# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data remove storage aj:temp args
execute store result storage aj:temp args.x int 1 store result score #this.x aj.i run data get entity @s Pos[0] 1
execute store result storage aj:temp args.y int 1 store result score #this.y aj.i run data get entity @s Pos[1] 1
execute store result storage aj:temp args.z int 1 store result score #this.z aj.i run data get entity @s Pos[2] 1
function animated_java:rocket/root/zzz/show_outdated_warning with storage aj:temp args
data modify entity @s data.rigHash set value 'acc3386f4e08d98fd0b1ec41d39cc23e0a95251ce4e4116e5841e9bef776567d'
execute on passengers run data merge entity @s {Glowing: 1b, glow_color_override: 16711680}
summon minecraft:text_display ~ ~ ~ { Tags:['aj.global.entity', 'aj.outdated_rig_text_display', 'aj.new'], text:["",{"text":"This rig instance is outdated!\\nIt will not function correctly and should be removed or re-summoned.","color":"red"}], alignment: 'center', billboard: 'vertical', transformation:{ translation:[0f,3f,0f], left_rotation:[0f,0f,0f,1f], right_rotation:[0f,0f,0f,1f], scale:[1f,1f,1f] } }
ride @e[type=minecraft:text_display,tag=aj.new,limit=1,distance=..0.01] mount @s
tag @e[type=minecraft:text_display,tag=aj.new,limit=1,distance=..0.01] remove aj.new