# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mech_legs.root] run return 0
execute on passengers if entity @s[tag=aj.mech_legs.data] unless data entity @s {data:{rigHash: '0f036544ec07317a349c8dcda0c0080d39b62927cb66650c9cb6d4e683607e31'}} on vehicle run function animated_java:mech_legs/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1