# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mech_legs.root] run return 0
execute on passengers if entity @s[tag=aj.mech_legs.data] unless data entity @s {data:{rigHash: '5ede22b532fb08528ae0ba3cc0dccc30659f118927395aed63fb539ee435008e'}} on vehicle run function animated_java:mech_legs/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1