# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mech_legs.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.mech_legs.animation.walking.playing] run function animated_java:mech_legs/animations/walking/zzz/on_tick
execute if entity @s[tag=aj.mech_legs.animation.walking_backwards.playing] run function animated_java:mech_legs/animations/walking_backwards/zzz/on_tick
execute if entity @s[tag=aj.mech_legs.animation.idle.playing] run function animated_java:mech_legs/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.mech_legs.animation.falling.playing] run function animated_java:mech_legs/animations/falling/zzz/on_tick
execute if entity @s[tag=aj.mech_legs.animation.landing.playing] run function animated_java:mech_legs/animations/landing/zzz/on_tick
execute on passengers if entity @s[tag=aj.mech_legs.data] run function animated_java:mech_legs/root/zzz/on_tick/locators_and_cameras
execute at @s on passengers run rotate @s ~ ~