# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_antenna) {transformation: [-1.6524f,0f,0f,0.0112f,0f,1.6524f,0f,-0.3464f,0f,0f,-1.6524f,-0.1672f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hexadecagon) {transformation: [-1f,0f,0f,-0.9878f,0f,1f,0f,-0.3464f,0f,0f,-1f,-0.7297f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hexadecagon2) {transformation: [-1f,0f,0f,-0.9878f,0f,1f,0f,-0.3464f,0f,0f,-1f,1.5203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hexadecagon3) {transformation: [-1f,0f,0f,1.0103f,0f,1f,0f,-0.3464f,0f,0f,-1f,1.5203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hexadecagon4) {transformation: [-1f,0f,0f,1.0103f,0f,1f,0f,-0.3464f,0f,0f,-1f,-0.7297f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_root) {transformation: [-2.2708f,0f,0f,-0.0112f,0f,2.2708f,0f,0.1589f,0f,0f,-2.2708f,0.0422f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}