# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_legs.node.foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_legs.node.leg_low] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_low set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_legs.node.bone4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_legs.node.leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_legs.node.foot2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_foot2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_legs.node.leg_low2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_low2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_legs.node.bone3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_legs.node.leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_legs.node.hips] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_hips set from storage aj:uuid main.out