# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.buggy.root] run return 0
execute on passengers if entity @s[tag=aj.buggy.data] unless data entity @s {data:{rigHash: '99c3a411bdff9a64c384117005130fd4786c2ba7a162d72355adb0910923c387'}} on vehicle run function animated_java:buggy/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1