# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.buggy.root] run return 0
execute on passengers if entity @s[tag=aj.buggy.data] unless data entity @s {data:{rigHash: 'ef9151b029b387b3b3baf7b9f4e90ccd56f50269f5a01824c629f7674125a4fd'}} on vehicle run function animated_java:buggy/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1