# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.buggy.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:buggy/as_root/pre_tick
execute if entity @s[tag=aj.buggy.animation.steer_left.playing] run function animated_java:buggy/animations/steer_left/zzz/on_tick
execute if entity @s[tag=aj.buggy.animation.steer_right.playing] run function animated_java:buggy/animations/steer_right/zzz/on_tick
execute if entity @s[tag=aj.buggy.animation.drive.playing] run function animated_java:buggy/animations/drive/zzz/on_tick
execute if entity @s[tag=aj.buggy.animation.drive_back.playing] run function animated_java:buggy/animations/drive_back/zzz/on_tick
execute on passengers if entity @s[tag=aj.buggy.data] run function animated_java:buggy/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:buggy/as_root/post_tick