# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.compressor.bone.piston_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_piston_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.compressor.bone.piston_middle] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_piston_middle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.compressor.bone.piston_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_piston_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.compressor.bone.root] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_root set from storage aj:uuid main.out