# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:mech_legs/animations/walking_backwards/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.walking_backwards.frame 1