# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.mech_torso.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mech_torso', 'function_path': 'animated_java:mech_torso/variants/default/apply'}
execute on passengers if entity @s[tag=aj.mech_torso.bone.jetpack2] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_jetpack2
execute on passengers if entity @s[tag=aj.mech_torso.bone.barrel1] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_barrel1
execute on passengers if entity @s[tag=aj.mech_torso.bone.barrel2] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_barrel2
execute on passengers if entity @s[tag=aj.mech_torso.bone.blaster_left] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_blaster_left
execute on passengers if entity @s[tag=aj.mech_torso.bone.sword_left] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_sword_left
execute on passengers if entity @s[tag=aj.mech_torso.bone.rocket_left] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_rocket_left
execute on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_left1] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_drillhead_left1
execute on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_left2] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_drillhead_left2
execute on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_left3] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_drillhead_left3
execute on passengers if entity @s[tag=aj.mech_torso.bone.drill_left] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_drill_left
execute on passengers if entity @s[tag=aj.mech_torso.bone.left_hand] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_left_hand
execute on passengers if entity @s[tag=aj.mech_torso.bone.left_arm_low] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_left_arm_low
execute on passengers if entity @s[tag=aj.mech_torso.bone.left_arm] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_left_arm
execute on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_right1] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_drillhead_right1
execute on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_right2] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_drillhead_right2
execute on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_right3] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_drillhead_right3
execute on passengers if entity @s[tag=aj.mech_torso.bone.drill_right] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_drill_right
execute on passengers if entity @s[tag=aj.mech_torso.bone.barrel3] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_barrel3
execute on passengers if entity @s[tag=aj.mech_torso.bone.barrel4] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_barrel4
execute on passengers if entity @s[tag=aj.mech_torso.bone.blaster_right] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_blaster_right
execute on passengers if entity @s[tag=aj.mech_torso.bone.rocket_right] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_rocket_right
execute on passengers if entity @s[tag=aj.mech_torso.bone.sword_right] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_sword_right
execute on passengers if entity @s[tag=aj.mech_torso.bone.right_hand] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_right_hand
execute on passengers if entity @s[tag=aj.mech_torso.bone.right_arm_low] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_right_arm_low
execute on passengers if entity @s[tag=aj.mech_torso.bone.right_arm] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_right_arm
execute on passengers if entity @s[tag=aj.mech_torso.bone.torso] run function animated_java:mech_torso/variants/default/zzz/apply_to_bone_torso
return 1