# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.fabricator.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'fabricator', 'function_path': 'animated_java:fabricator/animations/printer_print/stop'}
tag @s remove aj.fabricator.animation.printer_print.playing
scoreboard players set @s aj.printer_print.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:fabricator/animations/printer_print/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only