# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.mech_legs.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mech_legs', 'function_path': 'animated_java:mech_legs/variants/default/apply'}
execute on passengers if entity @s[tag=aj.mech_legs.bone.foot] run function animated_java:mech_legs/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.mech_legs.bone.leg_low] run function animated_java:mech_legs/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.mech_legs.bone.bone4] run function animated_java:mech_legs/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.mech_legs.bone.leg] run function animated_java:mech_legs/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.mech_legs.bone.foot2] run function animated_java:mech_legs/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.mech_legs.bone.leg_low2] run function animated_java:mech_legs/variants/default/zzz/5
execute on passengers if entity @s[tag=aj.mech_legs.bone.bone3] run function animated_java:mech_legs/variants/default/zzz/6
execute on passengers if entity @s[tag=aj.mech_legs.bone.leg2] run function animated_java:mech_legs/variants/default/zzz/7
execute on passengers if entity @s[tag=aj.mech_legs.bone.hips] run function animated_java:mech_legs/variants/default/zzz/8