# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.compressor.node.piston_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_piston_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.compressor.node.piston_middle] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_piston_middle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.compressor.node.piston_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_piston_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.compressor.node.root] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_root set from storage aj:uuid main.out