# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if data storage aj:temp {args:{animation:''}} run return run function animated_java:mech_torso/zzz/summon/animation_arg/zzz/2
execute store result storage aj:temp args.frame int 1 store result score #frame aj.i run data get storage aj:temp args.frame
execute if score #frame aj.i matches ..-1 run return run function animated_java:mech_torso/zzz/summon/animation_arg/zzz/3
execute store success score #success aj.i run function animated_java:mech_torso/zzz/summon/animation_arg/try_set_frame with storage aj:temp args
execute unless score #success aj.i matches 1 run return run function animated_java:mech_torso/zzz/summon/animation_arg/zzz/4 with storage aj:temp args
execute if data storage aj:temp {args:{start_animation: true}} run function animated_java:mech_torso/zzz/summon/animation_arg/start_animation with storage aj:temp args