# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.mech_torso.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mech_torso', 'function_path': 'animated_java:mech_torso/variants/gatling_right/apply'}
execute on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_right1] run function animated_java:mech_torso/variants/gatling_right/zzz/0
execute on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_right2] run function animated_java:mech_torso/variants/gatling_right/zzz/1
execute on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_right3] run function animated_java:mech_torso/variants/gatling_right/zzz/2
execute on passengers if entity @s[tag=aj.mech_torso.bone.drill_right] run function animated_java:mech_torso/variants/gatling_right/zzz/3
execute on passengers if entity @s[tag=aj.mech_torso.bone.barrel_right] run function animated_java:mech_torso/variants/gatling_right/zzz/4
execute on passengers if entity @s[tag=aj.mech_torso.bone.blaster_right] run function animated_java:mech_torso/variants/gatling_right/zzz/5
execute on passengers if entity @s[tag=aj.mech_torso.bone.rocket_right] run function animated_java:mech_torso/variants/gatling_right/zzz/6
execute on passengers if entity @s[tag=aj.mech_torso.bone.sword_right] run function animated_java:mech_torso/variants/gatling_right/zzz/7