# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:buggy/animations/drive_back/zzz/apply_frame {frame: 20}
scoreboard players add @s aj.drive_back.frame 1