# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_foot) {transformation: [-1f,0f,0f,0.782f,0f,1f,0f,-1.5951f,0f,0f,-1f,0.3376f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_low) {transformation: [-1f,0f,0f,0.8125f,0f,0.999f,0.0436f,-0.4646f,0f,0.0436f,-0.999f,0.1517f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [-1f,0f,0f,0.8125f,0f,0.2164f,0.9763f,-0.5738f,0f,0.9763f,-0.2164f,0.7449f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg) {transformation: [-1f,0f,0f,0.8227f,0f,0.5f,-0.866f,-0.1971f,0f,-0.866f,-0.5f,0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_foot2) {transformation: [-1f,0f,0f,-0.782f,0f,1f,0f,-1.5951f,0f,0f,-1f,0.3376f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_low2) {transformation: [-1f,0f,0f,-0.8125f,0f,0.999f,0.0436f,-0.4646f,0f,0.0436f,-0.999f,0.1517f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-1f,0f,0f,-0.8125f,0f,0.2164f,0.9763f,-0.5738f,0f,0.9763f,-0.2164f,0.7449f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.8227f,0f,0.5f,-0.866f,-0.1971f,0f,-0.866f,-0.5f,0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hips) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.1996f,0f,0f,-1f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"commands":{"posx":0,"posy":0,"posz":0,"roty":0,"rotx":0}}}