# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_foot) {transformation: [-1f,0f,0f,0.782f,0f,1f,0.0018f,-1.6299f,0f,0.0018f,-1f,0.3375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_low) {transformation: [-1f,0f,0f,0.8125f,0f,0.9992f,0.04f,-0.5f,0f,0.04f,-0.9992f,0.1475f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [-1f,0f,0f,0.8125f,0f,0.22f,0.9755f,-0.5866f,0f,0.9755f,-0.22f,0.7365f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg) {transformation: [-1f,0f,0f,0.8227f,0f,0.5189f,-0.8548f,-0.1971f,0f,-0.8548f,-0.5189f,0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_foot2) {transformation: [-1f,0f,0f,-0.782f,0f,1f,0.0018f,-1.6299f,0f,0.0018f,-1f,0.3375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_low2) {transformation: [-1f,0f,0f,-0.8125f,0f,0.9992f,0.04f,-0.5f,0f,0.04f,-0.9992f,0.1475f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-1f,0f,0f,-0.8125f,0f,0.22f,0.9755f,-0.5866f,0f,0.9755f,-0.22f,0.7365f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.8227f,0f,0.5189f,-0.8548f,-0.1971f,0f,-0.8548f,-0.5189f,0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}