# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_foot) {transformation: [-1f,0f,0f,0.782f,0f,1f,0.002f,-1.6788f,0f,0.002f,-1f,0.3372f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_low) {transformation: [-1f,0f,0f,0.8125f,0f,0.9994f,0.0348f,-0.55f,0f,0.0348f,-0.9994f,0.1413f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [-1f,0f,0f,0.8125f,0f,0.2251f,0.9743f,-0.6045f,0f,0.9743f,-0.2251f,0.7241f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg) {transformation: [-1f,0f,0f,0.8227f,0f,0.5453f,-0.8382f,-0.1971f,0f,-0.8382f,-0.5453f,0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_foot2) {transformation: [-1f,0f,0f,-0.782f,0f,1f,0.002f,-1.6788f,0f,0.002f,-1f,0.3372f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_low2) {transformation: [-1f,0f,0f,-0.8125f,0f,0.9994f,0.0348f,-0.55f,0f,0.0348f,-0.9994f,0.1413f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-1f,0f,0f,-0.8125f,0f,0.2251f,0.9743f,-0.6045f,0f,0.9743f,-0.2251f,0.7241f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.8227f,0f,0.5453f,-0.8382f,-0.1971f,0f,-0.8382f,-0.5453f,0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}