# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_foot) {transformation: [-1f,0f,0f,0.782f,0f,1f,0.0013f,-1.7367f,0f,0.0013f,-1f,0.3366f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_low) {transformation: [-1f,0f,0f,0.8125f,0f,0.9996f,0.0285f,-0.6092f,0f,0.0285f,-0.9996f,0.1336f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [-1f,0f,0f,0.8125f,0f,0.2311f,0.9729f,-0.6253f,0f,0.9729f,-0.2311f,0.7085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg) {transformation: [-1f,0f,0f,0.8227f,0f,0.5762f,-0.8173f,-0.1971f,0f,-0.8173f,-0.5762f,0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_foot2) {transformation: [-1f,0f,0f,-0.782f,0f,1f,0.0013f,-1.7367f,0f,0.0013f,-1f,0.3366f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_low2) {transformation: [-1f,0f,0f,-0.8125f,0f,0.9996f,0.0285f,-0.6092f,0f,0.0285f,-0.9996f,0.1336f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-1f,0f,0f,-0.8125f,0f,0.2311f,0.9729f,-0.6253f,0f,0.9729f,-0.2311f,0.7085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.8227f,0f,0.5762f,-0.8173f,-0.1971f,0f,-0.8173f,-0.5762f,0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}