# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_foot) {transformation: [-1f,0f,0f,0.782f,0f,1f,0f,-1.7986f,0f,0f,-1f,0.3355f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_low) {transformation: [-1f,0f,0f,0.8125f,0f,0.9998f,0.0218f,-0.6724f,0f,0.0218f,-0.9998f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [-1f,0f,0f,0.8125f,0f,0.2377f,0.9713f,-0.6472f,0f,0.9713f,-0.2377f,0.6907f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg) {transformation: [-1f,0f,0f,0.8227f,0f,0.6088f,-0.7934f,-0.1971f,0f,-0.7934f,-0.6088f,0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_foot2) {transformation: [-1f,0f,0f,-0.782f,0f,1f,0f,-1.7986f,0f,0f,-1f,0.3355f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_low2) {transformation: [-1f,0f,0f,-0.8125f,0f,0.9998f,0.0218f,-0.6724f,0f,0.0218f,-0.9998f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-1f,0f,0f,-0.8125f,0f,0.2377f,0.9713f,-0.6472f,0f,0.9713f,-0.2377f,0.6907f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.8227f,0f,0.6088f,-0.7934f,-0.1971f,0f,-0.7934f,-0.6088f,0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}