# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_foot) {transformation: [-1f,0f,0f,0.782f,0f,1f,-0.0013f,-1.8595f,0f,-0.0013f,-1f,0.334f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_low) {transformation: [-1f,0f,0f,0.8125f,0f,0.9999f,0.0151f,-0.7348f,0f,0.0151f,-0.9999f,0.116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [-1f,0f,0f,0.8125f,0f,0.2442f,0.9697f,-0.6684f,0f,0.9697f,-0.2442f,0.6721f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg) {transformation: [-1f,0f,0f,0.8227f,0f,0.6403f,-0.7681f,-0.1971f,0f,-0.7681f,-0.6403f,0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_foot2) {transformation: [-1f,0f,0f,-0.782f,0f,1f,-0.0013f,-1.8595f,0f,-0.0013f,-1f,0.334f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_low2) {transformation: [-1f,0f,0f,-0.8125f,0f,0.9999f,0.0151f,-0.7348f,0f,0.0151f,-0.9999f,0.116f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-1f,0f,0f,-0.8125f,0f,0.2442f,0.9697f,-0.6684f,0f,0.9697f,-0.2442f,0.6721f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.8227f,0f,0.6403f,-0.7681f,-0.1971f,0f,-0.7681f,-0.6403f,0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}