# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_foot) {transformation: [-1f,0f,0f,0.782f,0f,1f,-0.002f,-1.915f,0f,-0.002f,-1f,0.3324f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_low) {transformation: [-1f,0f,0f,0.8125f,0f,1f,0.0089f,-0.7916f,0f,0.0089f,-1f,0.1074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [-1f,0f,0f,0.8125f,0f,0.2502f,0.9682f,-0.6873f,0f,0.9682f,-0.2502f,0.6542f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg) {transformation: [-1f,0f,0f,0.8227f,0f,0.6685f,-0.7437f,-0.1971f,0f,-0.7437f,-0.6685f,0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_foot2) {transformation: [-1f,0f,0f,-0.782f,0f,1f,-0.002f,-1.915f,0f,-0.002f,-1f,0.3324f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_low2) {transformation: [-1f,0f,0f,-0.8125f,0f,1f,0.0089f,-0.7916f,0f,0.0089f,-1f,0.1074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-1f,0f,0f,-0.8125f,0f,0.2502f,0.9682f,-0.6873f,0f,0.9682f,-0.2502f,0.6542f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.8227f,0f,0.6685f,-0.7437f,-0.1971f,0f,-0.7437f,-0.6685f,0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}