# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.assembler.root] run return 0
execute on passengers if entity @s[tag=aj.assembler.data] unless data entity @s {data:{rigHash: 'f4e6357c57689cae97c0a00858b6570bcb0f55c2e3ac8e52c9b128f865d9d8b4'}} on vehicle run function animated_java:assembler/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1