# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.assembler.root] run return 0
execute on passengers if entity @s[tag=aj.assembler.data] unless data entity @s {data:{rigHash: '59ad9d7b30fac0fcc7207f18ccee71dc33beb4652d8ce91870be566f35e8d17f'}} on vehicle run function animated_java:assembler/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1