# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.button] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_button set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.text_display2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.text_display] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.text_display3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_text_display3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rocket.node.root] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_root set from storage aj:uuid main.out