# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.walking.frame dummy
scoreboard objectives add aj.walking_backwards.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.falling.frame dummy
scoreboard objectives add aj.landing.frame dummy