# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:mech_torso/animations/empty_shield/zzz/apply_frame {frame: 20}
scoreboard players add @s aj.empty_shield.frame 1