# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.buggy.node.antenna] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_antenna set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.buggy.node.hexadecagon] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_hexadecagon set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.buggy.node.hexadecagon2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_hexadecagon2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.buggy.node.hexadecagon3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_hexadecagon3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.buggy.node.hexadecagon4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_hexadecagon4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.buggy.node.root] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_root set from storage aj:uuid main.out