# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.jetpack2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_jetpack2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.ammo_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_ammo_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.ammo_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_ammo_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.health] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.text_display_health set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.barrel1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_barrel1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.barrel2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_barrel2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.blaster_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_blaster_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.sword_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_sword_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.rocket_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rocket_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.drillhead_left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_drillhead_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.drillhead_left2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_drillhead_left2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.drillhead_left3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_drillhead_left3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.drill_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_drill_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.left_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.left_arm_low] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_arm_low set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.drillhead_right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_drillhead_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.drillhead_right2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_drillhead_right2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.drillhead_right3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_drillhead_right3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.drill_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_drill_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.barrel3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_barrel3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.barrel4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_barrel4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.blaster_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_blaster_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.rocket_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_rocket_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.sword_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_sword_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.right_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.right_arm_low] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_arm_low set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.mech_torso.node.torso] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_torso set from storage aj:uuid main.out