# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_arm_z) {transformation: [-1.0208f,0f,0f,-0.2917f,0f,1.0208f,0f,-0.9557f,0f,0f,-1.0208f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_nozzle) {transformation: [-1.0833f,0f,0f,-0.2917f,0f,1.0833f,0f,-0.9557f,0f,0f,-1.0833f,0.0712f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_arm_x) {transformation: [-1.0208f,0f,0f,0f,0f,1.0208f,0f,-0.9557f,0f,0f,-1.0208f,0.1337f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_frame) {transformation: [-1f,0f,0f,-0.3125f,0f,1f,0f,0.5443f,0f,0f,-1f,0.3308f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_product) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.6432f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}