# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.mech_torso.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'mech_torso', 'function_path': 'animated_java:mech_torso/variants/empty_both/apply'}
execute on passengers if entity @s[tag=aj.mech_torso.bone.barrel_left] run function animated_java:mech_torso/variants/empty_both/zzz/0
execute on passengers if entity @s[tag=aj.mech_torso.bone.blaster_left] run function animated_java:mech_torso/variants/empty_both/zzz/1
execute on passengers if entity @s[tag=aj.mech_torso.bone.sword_left] run function animated_java:mech_torso/variants/empty_both/zzz/2
execute on passengers if entity @s[tag=aj.mech_torso.bone.rocket_left] run function animated_java:mech_torso/variants/empty_both/zzz/3
execute on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_left1] run function animated_java:mech_torso/variants/empty_both/zzz/4
execute on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_left2] run function animated_java:mech_torso/variants/empty_both/zzz/5
execute on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_left3] run function animated_java:mech_torso/variants/empty_both/zzz/6
execute on passengers if entity @s[tag=aj.mech_torso.bone.drill_left] run function animated_java:mech_torso/variants/empty_both/zzz/7
execute on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_right1] run function animated_java:mech_torso/variants/empty_both/zzz/8
execute on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_right2] run function animated_java:mech_torso/variants/empty_both/zzz/9
execute on passengers if entity @s[tag=aj.mech_torso.bone.drillhead_right3] run function animated_java:mech_torso/variants/empty_both/zzz/10
execute on passengers if entity @s[tag=aj.mech_torso.bone.drill_right] run function animated_java:mech_torso/variants/empty_both/zzz/11
execute on passengers if entity @s[tag=aj.mech_torso.bone.barrel_right] run function animated_java:mech_torso/variants/empty_both/zzz/12
execute on passengers if entity @s[tag=aj.mech_torso.bone.blaster_right] run function animated_java:mech_torso/variants/empty_both/zzz/13
execute on passengers if entity @s[tag=aj.mech_torso.bone.rocket_right] run function animated_java:mech_torso/variants/empty_both/zzz/14
execute on passengers if entity @s[tag=aj.mech_torso.bone.sword_right] run function animated_java:mech_torso/variants/empty_both/zzz/15