# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.fabricator.root] run return 0
execute on passengers if entity @s[tag=aj.fabricator.data] unless data entity @s {data:{rigHash: '2ea9da40e914d8ce2c566ea5e5aa8b2ebbadfb35503c68de5209c5c407f9d3b2'}} on vehicle run function animated_java:fabricator/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1