# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.fabricator.root] run return 0
execute on passengers if entity @s[tag=aj.fabricator.data] unless data entity @s {data:{rigHash: '3e15e7669fdef4b7fd06aac5aba99f496c1b25b8f2e7eeccaea2cf0e421424ac'}} on vehicle run function animated_java:fabricator/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1