# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run data modify entity @s interpolation_duration set value 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.rocket.button_push.frame
function animated_java:rocket/animations/rocket.button_push/zzz/apply_frame with storage aj:temp args
execute if score @s aj.rocket.button_push.frame matches 5 run return run function animated_java:rocket/animations/rocket.button_push/stop
scoreboard players add @s aj.rocket.button_push.frame 1