# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if data storage aj:temp {args:{variant:''}} run return run function animated_java:mech_torso/zzz/summon/variant_arg/zzz/0
execute store success score #success aj.i run function animated_java:mech_torso/zzz/summon/variant_arg/try_apply with storage aj:temp args
execute unless score #success aj.i matches 1 run return run function animated_java:mech_torso/zzz/summon/variant_arg/zzz/1 with storage aj:temp args