# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute if function animated_java:mech_torso/variants/$(variant)/apply run return 1
return fail