# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on vehicle on passengers if entity @s[tag=exp.left_arm_control] run tag @s add exp.shoot
execute on vehicle on passengers if entity @s[tag=exp.left_arm_control] run tag @s add exp.shoot_right