# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.bone21] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone21 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.arm4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.small_arm_base4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_small_arm_base4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.bone25] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone25 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.bone16] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone16 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.arm3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.small_arm_base3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_small_arm_base3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.bone15] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone15 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.bone26] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone26 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.arm5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.small_arm_base5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_small_arm_base5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.bone20] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone20 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.bone11] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone11 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.small_arm_base2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_small_arm_base2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.bone2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.ring] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ring set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.wheel] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheel set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.wheel2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheel2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.rails] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rails set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.wheel3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheel3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.wheel4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wheel4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.rails2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rails2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.bone6] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.bone5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.bone4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.bone3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.octagon] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_octagon set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.machine_arm_root] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_machine_arm_root set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.bone10] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.bone9] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.bone8] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.bone7] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bone7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.octagon2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_octagon2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.machine_arm_root2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_machine_arm_root2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.assembler.bone.base] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_base set from storage aj:uuid main.out