# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.rocket.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'rocket', 'function_path': 'animated_java:rocket/animations/pause_all'}
tag @s remove aj.rocket.animation.rocket.button_push.playing
tag @s remove aj.rocket.animation.rocket.setup_text.playing