# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.rocket.root] run return 0
execute on passengers if entity @s[tag=aj.rocket.data] unless data entity @s {data:{rigHash: '487e9b256ebaa223c899a6184eae52d0f38260ad0434d6b3b480fa0b25592bb5'}} on vehicle run function animated_java:rocket/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1