# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.rocket.root] run return 0
execute on passengers if entity @s[tag=aj.rocket.data] unless data entity @s {data:{rigHash: 'acc3386f4e08d98fd0b1ec41d39cc23e0a95251ce4e4116e5841e9bef776567d'}} on vehicle run function animated_java:rocket/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1