# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_foot) {transformation: [-1f,0f,0f,0.782f,0f,0.7373f,-0.6756f,-2.044f,0f,-0.6756f,-0.7373f,1.2833f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_low) {transformation: [-1f,0f,0f,0.8125f,0f,0.887f,-0.4617f,-1.1579f,0f,-0.4617f,-0.887f,0.5571f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [-1f,0f,0f,0.8125f,0f,0.9537f,0.3007f,-0.6235f,0f,0.3007f,-0.9537f,0.7099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg) {transformation: [-1f,0f,0f,0.8227f,0f,0.5736f,-0.8192f,-0.1971f,0f,-0.8192f,-0.5736f,0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_foot2) {transformation: [-1f,0f,0f,-0.782f,0f,0.7373f,-0.6756f,-2.044f,0f,-0.6756f,-0.7373f,1.2833f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_low2) {transformation: [-1f,0f,0f,-0.8125f,0f,0.887f,-0.4617f,-1.1579f,0f,-0.4617f,-0.887f,0.5571f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-1f,0f,0f,-0.8125f,0f,0.9537f,0.3007f,-0.6235f,0f,0.3007f,-0.9537f,0.7099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2) {transformation: [-1f,0f,0f,-0.8227f,0f,0.5736f,-0.8192f,-0.1971f,0f,-0.8192f,-0.5736f,0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_hips) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.1996f,0f,0f,-1f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"commands":{"posx":0,"posy":0,"posz":0,"roty":0,"rotx":0}}}