# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mech_torso.root] run return 0
execute on passengers if entity @s[tag=aj.mech_torso.data] unless data entity @s {data:{rigHash: '15f08e34962f2b615772ef60220adf04333b5ecc0945491b20d378df0d738eee'}} on vehicle run function animated_java:mech_torso/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1