# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.enhancer.node.bone2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.enhancer.node.scanner] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_scanner set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.enhancer.node.bone] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bone set from storage aj:uuid main.out