# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.compressor.root] run return 0
execute on passengers if entity @s[tag=aj.compressor.data] unless data entity @s {data:{rigHash: '6039a257f4bdd1816dae074531643764eacdf7a7a7b69703cbbfba29800074af'}} on vehicle run function animated_java:compressor/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1