# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.compressor.root] run return 0
execute on passengers if entity @s[tag=aj.compressor.data] unless data entity @s {data:{rigHash: '515609e4040d607a559276b124a71793fcfa5ca3dff3243be50301e9930add83'}} on vehicle run function animated_java:compressor/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1